server:
  port: 8091 
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DBiTest-on
    
    username: postgres
    password: postgresql2021
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: drop-and-create
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    